title: "Benson Kiprotich Kipsang â€” CV & Portfolio"
description: "Cybersecurity & Digital Forensics Student"
remote_theme: "mmistakes/minimal-mistakes"

url: "https://bensonsang.github.io"
baseurl: "" # leave empty if this is your main profile site

# Optional profile info
author:
  name: "Benson K Kipsang"
  avatar: "/assets/images/profile.jpg"
  bio: "Cybersecurity Student | Ethical Hacking Learner | Web Developer"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/BENSONSANG"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/kkbenson"

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/

# Layout defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: "true"
